
 classDiagram 
    direction RL






PreTraining__Task ..> vocabulary__Data  : USES
PreTraining__Task ..> openWebText__Data  : USES
PreTraining__Task ..> GPT2TrainingConfig__SoftwareFile  : USES





PreTraining__Task ..> nanoGPT_Model__MLModel  : GENERATES
PreTraining__Task ..> GPT2ModelWeights__SoftwareFile  : GENERATES



Tokenizing__Task ..> PreTraining__Task  : NEXT





Tokenizing__Task ..> GPT2TokenizerCode__SoftwareFile  : USES
Tokenizing__Task ..> openWebText__Data  : USES



Tokenizing__Task ..> vocabulary__Data  : GENERATES



DataCollection__Task ..> Tokenizing__Task  : NEXT



DataCollection__Task ..> openWebText__Data  : GENERATES

class GPT2TrainingConfig__SoftwareFile{
    uid : 1351da19-f34a-4a23-9d43-3464d6...
    type : SoftwareFile
    name : GPT2TrainingConfig
    properties : description: Training the GPT2 model using collected data \n		 optimizer: &#123;&#39;type&#39;: &#39;adamw&#39;, &#39;weight_decay&#39;: 0.1, &#39;beta1&#39;: 0.9, &#39;beta2&#39;: 0.95, &#39;notes&#39;: &#39;Weight decay is not applied to bias and layer norm layers&#39;&#125; \n		 model_config: &#123;&#39;type&#39;: &#39;decoder&#39;, &#39;n_parameters&#39;: 124439808, &#39;n_active_parameters&#39;: 124439808, &#39;n_embedding_dimensions&#39;: 768, &#39;n_transformers&#39;: 12, &#39;positional_embedding&#39;: &#123;&#39;type&#39;: &#39;learned&#39;, &#39;n_positions&#39;: 1024&#125;, &#39;transformer_attention&#39;: &#123;&#39;type&#39;: &#39;multi-head-attention&#39;, &#39;n_heads&#39;: 12&#125;, &#39;transformer_ffn&#39;: &#123;&#39;hidden_layer_size&#39;: 3072, &#39;hidden_layer_size_ratio&#39;: 4.0&#125;&#125;
    category : config
    software_fileKind : FILE
}

class GPT2ModelWeights__SoftwareFile{
    uid : c3219963-b9c3-4249-b3e4-c093c9...
    type : SoftwareFile
    name : GPT2ModelWeights
    properties : location: https://openaipublic.blob.core.windows.net/gpt-2/models/124M/model.ckpt.data-00000-of-00001 \n		 n_parameters: 124439808
    category : model_weights
    software_fileKind : FILE
}

class GPT2TokenizerCode__SoftwareFile{
    uid : 90308e79-acd4-4494-97bf-7a8062...
    type : SoftwareFile
    name : GPT2TokenizerCode
    properties : reference_implementation: https://github.com/openai/tiktoken/blob/main/tiktoken_ext/openai_public.py \n		 pre_tokenization:: to encode
    software_fileKind : FILE
    contentType : text/x-python
}

class vocabulary__Data{
    uid : 434b814b-9617-4650-8c67-aaf212...
    type : Data
    name : vocabulary
    description : The generated ...
    properties : code_ref: https://github.com/jcpeterson/openwebtext \n		 n_vocab: 50257
    access : private
    license : none
    category : vocabulary
    software_fileKind : FILE
    contentType : text/plain
    software_downloadLocation : https://openaipublic.blob.core...
    dataset_kinds : dataset
    data_formats : text, bpe
    dataset_hasSensitivePersonalInformation : yes
}

class openWebText__Data{
    uid : 36a721d9-0f92-40dd-b5f9-3bb2e1...
    type : Data
    name : openWebText
    description : a reconstructed &#39;open&#39; version...
    properties : code_ref: https://github.com/jcpeterson/openwebtext
    access : private
    license : none
    software_fileKind : FILE
    software_downloadLocation : https://huggingface.co/dataset...
    data_types : text
    dataset_kinds : corpus
    data_formats : .txt
    dataset_hasSensitivePersonalInformation : yes
}

class nanoGPT_Model__MLModel{
    uid : 2da322ff-0acd-417d-b542-ca29c2...
    type : MLModel
    name : nanoGPT Model
    properties : model_type: GPT2 \n		 framework: PyTorch \n		 model_size: 124M
    software_fileKind : FILE
}

class PreTraining__Task{
    uid : f0062466-9173-49c7-858c-550de5...
    type : Task
    name : PreTraining
    description : Pre-training the GPT2 model us...
}

class Tokenizing__Task{
    uid : a288db6c-ad63-46a6-9e26-08876f...
    type : Task
    name : Tokenizing
    description : Tokenizing the training data u...
    properties : family: byte-bpe-tokenizer
}

class DataCollection__Task{
    uid : 8eed3374-c711-4695-b6e0-03cd16...
    type : Task
    name : DataCollection
    description : Collecting the training data f...
}

class inst_4341953088__Pipeline{
    uid : nanoGPT Pipeline
    type : Pipeline
}
inst_4341953088__Pipeline --> DataCollection__Task  : tasks
inst_4341953088__Pipeline --> Tokenizing__Task  : tasks
inst_4341953088__Pipeline --> PreTraining__Task  : tasks

class inst_4341981280__Manifest{
    uid : nanoGPT manifest
    type : Manifest
}
inst_4341981280__Manifest --> inst_4341953088__Pipeline  : pipeline
inst_4341981280__Manifest --> nanoGPT_Model__MLModel  : artefacts
inst_4341981280__Manifest --> openWebText__Data  : artefacts
inst_4341981280__Manifest --> vocabulary__Data  : artefacts
inst_4341981280__Manifest --> GPT2TokenizerCode__SoftwareFile  : artefacts
inst_4341981280__Manifest --> GPT2ModelWeights__SoftwareFile  : artefacts
inst_4341981280__Manifest --> GPT2TrainingConfig__SoftwareFile  : artefacts

style inst_4341981280__Manifest fill:#fff3e0,stroke:#e65100,stroke-width:1px,stroke-dasharray: 5 5
style inst_4341953088__Pipeline fill:#e1f5fe,stroke:#01579b,stroke-width:2px
style DataCollection__Task fill:#e1f5fe,stroke:#01579b,stroke-width:2px
style Tokenizing__Task fill:#e1f5fe,stroke:#01579b,stroke-width:2px
style PreTraining__Task fill:#e1f5fe,stroke:#01579b,stroke-width:2px
style nanoGPT_Model__MLModel fill:#fff3e0,stroke:#e65100,stroke-width:1px,stroke-dasharray: 5 5
style openWebText__Data fill:#fff3e0,stroke:#e65100,stroke-width:1px,stroke-dasharray: 5 5
style vocabulary__Data fill:#fff3e0,stroke:#e65100,stroke-width:1px,stroke-dasharray: 5 5
style GPT2TokenizerCode__SoftwareFile fill:#fff3e0,stroke:#e65100,stroke-width:1px,stroke-dasharray: 5 5
style GPT2ModelWeights__SoftwareFile fill:#fff3e0,stroke:#e65100,stroke-width:1px,stroke-dasharray: 5 5
style GPT2TrainingConfig__SoftwareFile fill:#fff3e0,stroke:#e65100,stroke-width:1px,stroke-dasharray: 5 5