@startuml
left to right direction

skinparam note {
    BackgroundColor #FEFECE
    BorderColor #A80036
}

'-------------- Actors -------------
"Data Scientist" as DS #lightyellow
"ML Engineer" as Dev #lightgreen



' ------------- Use Cases -------------

'note top of FS : Defines the framework for verifying FATES properties
rectangle "PROFIL system" as PS{
    CheckQuality as (Check Quality) #lightyellow
    Explore as (Explore the ML landscape) #lightyellow
    Instrument as (Define  rules to check) #lightyellow
    GenDoc as (Generate PROFIL documentation) #lightblue
    Abstract as (Abstract Pipeline representation) #lightblue
}
note bottom of PS : Engine for \nlinting and static analysis


'-------------- Relations -------------


'-------------- Data Scientist -------------
DS --> Explore
Dev --> Abstract
DS --> Instrument
Dev --> CheckQuality
'DS --> CheckQuality
Instrument ..> CheckQuality :extends
':Dev: --> GenDoc
Abstract <.. GenDoc :extends
GenDoc ..> CheckQuality :extends

DS --|> Dev

@enduml

'Préciser les requirements FATEs du ML
"Domain Expert" as DomainExpert #lightgreen

rectangle "FATEs Justification System" as FS {
    Collect as (Collect FATEs requirements) #lightgreen
    GenJustModel as (Generate a Justification Model) #lightgreen
    Verify as (Check FATEs properties) #lightgreen
    GenJust as (Generate Justification) #lightgreen

    CollectEvidence as (Collect evidence) #lightgreen
    InstrumentCI as (Instrument the CI/CD pipeline to justify) #lightgreen

    Register as (Register a ML description) #lightblue
    Extract as (Extract/filter ML descriptions) #lightblue
    Manage as (Manage ML descriptions) #lightblue
    Generate as (Generate ML description) #lightblue

    DefineRule as (Define FATES rules to check) #lightgreen


}

:DomainExpert: --> GenJustModel

"ML Provider" as MLProvider
note right of MLProvider : Publishes the consolidated \nresults of Data Scientist and ML engineer work.
':Dev: --> Verify
InstrumentCI --> Verify:includes
InstrumentCI --> GenJust:includes
:Dev: --> InstrumentCI

CheckQuality  <.. Verify:extends

'note on link : FATEs verification specializes \ngeneric quality checks
':Dev: --> GenJust

'ML provider
:MLProvider: --> Manage
':MLProvider: --> GenDoc



Manage<..Generate   :extends
Manage<..Extract   :extends
Manage<..Register   :extends
Generate <.. Register :extends

Instrument <.. DefineRule :extends
 Manage <.. GenJust :extends

'Verify <.. GenJust :extends


DS <|-- MLProvider
Dev <|-- DS