@startuml
left to right direction

skinparam note {
    BackgroundColor #FEFECE
    BorderColor #A80036
}


'-------------- Actors -------------
"Data Scientist" as DSP #lightyellow
"Data Scientist" as DSF #lightgreen
"Data Scientist" as DSE #lightblue


"ML Provider" as MLProviderE #lightblue
"ML Provider" as MLProviderF #lightgreen

"ML Engineer" as Dev #lightgreen


"ML Consumer" as MLConsumer #lightblue
note top of MLConsumer : Looks for ML descriptions to explore the ML landscape and make informed decisions.
note top of MLProviderF : Publishes the consolidated \nresults of Data Scientist and ML engineer work.

"Domain Expert" as DomainExpert #lightgreen




' ------------- Use Cases -------------
'Préciser les requirements FATEs du ML
rectangle "FATEs Justification System" as FS {
    CollectReq as (Collect FATEs requirements) #lightgreen
    GenJustModel as (Generate a Justification Model) #lightgreen
    Verify as (Check FATEs properties) #lightgreen
    GenJust as (Generate Justification) #lightgreen


    CollectEvidence as (Gather evidence) #lightgreen
    InstrumentCI as (Automate Justification within CI/CD) #lightgreen

    DefineRule as (Define new FATES rules to check) #lightgreen
}
DefineRule ..> Verify :extends

DSF --> DefineRule
MLProviderF ..> GenJust


'note top of FS : Defines the framework for verifying FATES properties
rectangle "PROFIL system" as PS{
    CheckQuality as (Check Quality) #lightyellow

    DefineQualityRule as (Define new quality rule) #lightyellow
    'GenDoc as (Generate Documentation)
    'BasedOnConstruction as (based on construction criteria) #lightblue
    ExtractMLProfile as (Extract ML descriptions from code) #lightyellow
    CheckMLArchitecture as (Check ML architecture) #lightyellow
    CheckMLCode as (Check ML code quality) #lightyellow
    'CheckMLDescription as (Check ML description) #lightblue
}
'note bottom of PS : Engine for \nlinting and static analysis

DefineQualityRule ..> CheckQuality :extends
DSP --> CheckQuality
DSP --> DefineQualityRule
DSP --> ExtractMLProfile


rectangle "Exploration System" as ES {
    EnhanceRules as (Enhance rules to validate ML description) #PaleTurquoise
    ExploreMLDescription as (Explore ML descriptions) #lightblue
    Compare as (Compare/filter ML Descriptions) #lightblue
    CompareConstruction as (according to Construction Criteria) #lightblue
    CompareFATES as (according to FATES properties) #lightblue
    Explore as (Explore the ML landscape) #lightblue
    note bottom of Explore
      allows the data scientist to navigate through the ML landscape,
      understand the characteristics of different ML descriptions,
      and produce insights such as building new rules.
      It includes dedicated visualization tools
      such as dashboards, heatmap, and interactive interfaces
       to facilitate the exploration process.
    end note

    ManageOne  as(Manage one ML description) #LightCyan
    WriteMLDescription as (Write a ML description) #LightCyan
    ReadMLDescription as (Read a ML description) #LightCyan
    note bottom of (ReadMLDescription)
      translates the ML description into
         structured formats (e.g., JSON, YAML) for interoperability
         or graphical representation for better understanding.
    end note
    ExtractMLDescription as (Extract ML description) #LightCyan
    note bottom of (ExtractMLDescription)
      extract the ML description
      according to different artefacts (e.g., code, data, BOM, modelcard,..).
    end note
    ValidateMLDescription as (Validate ML description) #LightCyan
    note bottom of (ValidateMLDescription)
        ensures the ML description's completeness, and consistency
        using automated checks and validation rules,
        and provides a report that can be part of the ML Description
        and feedbacks to the ML provider for improvement.
    end note
    RegisterMLDescription as (Register a ML description) #LightCyan

 }
 '------------------- manage one ML Description
 MLProviderE --> ManageOne
    WriteMLDescription ..> ManageOne:extends
    ReadMLDescription ..> ManageOne:extends
    ExtractMLDescription ..> ManageOne:extends
    ValidateMLDescription ..> ManageOne:extends
    RegisterMLDescription ..> ManageOne:extends

ExtractMLProfile --> ExtractMLDescription #blue;line.dotted;text:blue

 '------------------- Explore ML Descriptions
 MLConsumer --> ExploreMLDescription
    Compare ..> ExploreMLDescription:extends
       Compare <.. CompareConstruction :extends
       Compare <.. CompareFATES :extends
Explore ..> ExploreMLDescription:extends
DSE --> Explore
DefineRule ..> EnhanceRules#blue;line.dotted;text:blue
DefineQualityRule ..> EnhanceRules#blue;line.dotted;text:blue


MLConsumer --> ValidateMLDescription

DSE --> EnhanceRules





'-------------- Relations -------------

:DomainExpert: --> GenJustModel
GenJustModel <.. CollectReq :extends
':DomainExpert: --> (Audit Justification)

:Dev: --> CollectEvidence
:Dev: --> InstrumentCI

InstrumentCI --> Verify:includes

CompareConstruction <.. CheckQuality #blue;line.dotted;text:blue
CheckMLArchitecture --|> CheckQuality
CheckMLCode --|> CheckQuality





@enduml
Dev --> (Filter LLMs by business criteria)
DS --> (Filter LLMs Based on Model Construction Criteria )
DS --> (Compare LLMs according to Construction Criteria)
DS --> (Check some properties of LLMs)
DS --> (Explore LLM Documentation)
(Compare LLMs according to Construction Criteria) <.. (Visualize the LLM Construction Workflow):extends
Admin --> (Enrich the LLM Metadata Schema )
Admin --> (Configure Verification-Based LLM Criteria)
DS --> (Compare LLM Construction Workflows)
(Compare LLM Construction Workflows) <.. (Visualize the LLM Construction Workflow):extends

