
 classDiagram
     direction LR

class inst_4329851360__Relationship{
    uid : 10ba86b7-f573-47e9-bf45-b54b128e5b91
    type : Element
    relationshipType : EVALUATES
}
inst_4329851360__Relationship --> inst_4329850816__Step  : from_
inst_4329851360__Relationship --> Confusion_Matrix__Metric  : to_


class inst_4329430704__Relationship{
    uid : a67b1d9e-11da-48f6-8be9-d08e12157bd8
    type : Element
    relationshipType : EVALUATES
}
inst_4329430704__Relationship --> inst_4329850816__Step  : from_
inst_4329430704__Relationship --> Model_Accuracy__Metric  : to_


class inst_4329804320__Relationship{
    uid : 8cc111df-da46-4a63-87c8-ea062314db11
    type : Element
    relationshipType : GENERATES
}
inst_4329804320__Relationship --> inst_4329851088__Step  : from_
inst_4329804320__Relationship --> Evaluation_Visualization__SoftwareFile  : to_


class inst_4329803408__Relationship{
    uid : 6056d29a-c9e8-4f67-8201-ffd8132fcc51
    type : Element
    relationshipType : GENERATES
}
inst_4329803408__Relationship --> inst_4329430416__Step  : from_
inst_4329803408__Relationship --> Trained_Decision_Tree_Model__SoftwareFile  : to_


class inst_4329412624__Relationship{
    uid : e33534a9-2005-425e-8567-8d13a7611c08
    type : Element
    relationshipType : GENERATES
}
inst_4329412624__Relationship --> inst_4329411984__Step  : from_
inst_4329412624__Relationship --> output_visualization__SoftwareFile  : to_


class inst_4329411664__Relationship{
    uid : 2db46a9e-9831-4c3e-9e7e-c5980a4ecd91
    type : Element
    relationshipType : DEPENDS_ON
}
inst_4329411664__Relationship --> inst_4329411344__Step  : from_
inst_4329411664__Relationship --> Iris_Flower_Dataset__Data  : to_


class inst_4329507872__Relationship{
    uid : 28ad3f63-03c2-4687-bad2-bd05a4fe6a6b
    type : Element
    relationshipType : SOURCE
}
inst_4329507872__Relationship --> Iris_Analysis_Pipeline_Manifest__PipelineManifest  : from_
inst_4329507872__Relationship --> inst_4329507536__SoftwareFile  : to_
class Confusion_Matrix__Metric{
    uid : 242829d3-8a7e-4b7d-878b-e35e77340208
    type : Element
    name : Confusion Matrix
    description : Matrice de confusion du modèle de classification sur le dataset IRIS.
    properties : calculation_method: confusion_matrix from scikit-learn
}
class Model_Accuracy__Metric{
    uid : af603361-3875-4e83-b22a-a79575e82e0a
    type : Element
    name : Model Accuracy
    description : Accuracy du modèle de classification sur le dataset IRIS.
    properties : calculation_method: accuracy_score from scikit-learn
}
class Evaluation_Visualization__SoftwareFile{
    uid : 2f3eb37a-38a6-438d-bf41-41a0d546d8e4
    type : Element
    name : Evaluation Visualization
    description : Result from excution , Content Preview: Matrice de Confusion
    properties : Content Preview: DecisionTreeClassifier(random_state=42)
    software_fileKind : FILE
}
class inst_4329413264__CreationInfo{
    createdBy : Data Scientist
    type : CreationInfo
    createdOn : 2024-06-24T10:00:00Z
}
class Trained_Decision_Tree_Model__SoftwareFile{
    uid : 84c2ef84-257a-4a4f-867a-349e26733741
    type : Element
    name : Trained Decision Tree Model
    description : Un modèle de classification entraîné sur le dataset IRIS.
    properties : model_type: Decision Tree
    software_fileKind : FILE
    software_primaryPurpose : Classification
    contentType : application/octet-stream
    software_downloadLocation : https://example.com/downloads/iris_decision_tree_model.bin
    external_reference : https://doi.org/10.1234/iris-model
}
Trained_Decision_Tree_Model__SoftwareFile --> inst_4329413264__CreationInfo  : creationInfo
class output_visualization__SoftwareFile{
    uid : bf69cd6c-0825-4693-a0b9-5d8b897f7981
    type : Element
    name : output_visualization
    description : visualisation Stream to stdout, Content Preview: sepal length...
    software_fileKind : FILE
}
class inst_4329509216__CreationInfo{
    createdBy : R.A. Fisher
    type : CreationInfo
    createdOn : 1936-01-01
}
class Iris_Flower_Dataset__Data{
    uid : 54a21d5b-5a80-449e-aeba-e8e1092fc48c
    type : Element
    name : Iris Flower Dataset
    description : Dataset classique de Fisher contenant 150 instances de 3 espèces d&#39;iris &#40;Setosa, Versicolor, Virginica&#41;.
    properties : num_instances: 150 | num_features: 4 | num_classes: 3 | feature_names: ['sepal length', 'sepal width', 'petal length', 'petal width'] | class_names: ['setosa', 'versicolor', 'virginica']
    software_fileKind : FILE
    software_primaryPurpose : Classification and Pattern Recognition
    contentType : text/csv
    software_downloadLocation : https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data
    external_reference : https://doi.org/10.24432/C56P4B
    data_languages : English
    data_types : tabular
    data_kinds : dataset
    datasetSize : 4550
    datasetAvailability : public
    dataset_hasSensitivePersonalInformation : no
    dataset_intendedUse : Training and evaluation of classification models.
    dataset_knownBias : Class balanced 50 samples per class
}
Iris_Flower_Dataset__Data --> inst_4329509216__CreationInfo  : creationInfo
class inst_4329506864__ExternalReference{
    externalIdentifierType : url
    identifier : nbpath
}
class inst_4329507536__SoftwareFile{
    uid : a7f4287c-7b12-4ceb-a0d3-7bb834f63311
    type : Element
    software_fileKind : FILE
    contentType : Jupiter Notebook
    languages : english, french, python
}
inst_4329507536__SoftwareFile --> inst_4329506864__ExternalReference  : external_reference
class inst_4329534032__Instruction{
    uid : 154dce6f-5583-41e0-86f4-9b0d21715d65
    type : Element
    shell : python
    code : plt.show&#40;&#41;
}
class inst_4329533872__Instruction{
    uid : 2f9b96ed-468c-4f50-8669-4015f1c812ab
    type : Element
    shell : python
    code : plt.title&#40;&#39;Matrice de Confusion&#39;&#41;
}
class inst_4329533712__Instruction{
    uid : 8c114714-e18c-4512-b7fc-3a29874f2f24
    type : Element
    shell : python
    code : plt.ylabel&#40;&#39;Valeur réelle&#39;&#41;
}
class inst_4329533552__Instruction{
    uid : 40cfdedd-d5fc-40de-95cc-007c0be18319
    type : Element
    shell : python
    code : plt.xlabel&#40;&#39;Prédiction&#39;&#41;
}
class inst_4329533392__Instruction{
    uid : b95dd90a-dd07-4acc-89d6-8c04c503d965
    type : Element
    shell : python
    code : plt.figure&#40;figsize=&#40;8, 6&#41;&#41;
}
class inst_4329533232__Instruction{
    uid : 54738aa0-6667-4a4e-b22a-212a3acf59f8
    type : Element
    shell : python
    code : plt.figure&#40;figsize=&#40;8, 6&#41;&#41;
}
class inst_4329851088__Step{
    uid : Visualize
    type : Element
}
inst_4329851088__Step --> inst_4329533232__Instruction  : commands
inst_4329851088__Step --> inst_4329533392__Instruction  : commands
inst_4329851088__Step --> inst_4329533552__Instruction  : commands
inst_4329851088__Step --> inst_4329533712__Instruction  : commands
inst_4329851088__Step --> inst_4329533872__Instruction  : commands
inst_4329851088__Step --> inst_4329534032__Instruction  : commands
class inst_4329533072__Instruction{
    uid : 4db29726-edb1-4a26-908d-2c3883cd7974
    type : Element
    shell : python
    code : cm = confusion_matrix&#40;y_test, predictions&#41;
}
class inst_4329532912__Instruction{
    uid : 3dd67263-f26e-469a-a05a-46177698a6ba
    type : Element
    shell : python
    code : print&#40;classification_report&#40;y_test, predictions&#41;&#41;
}
class inst_4329532752__Instruction{
    uid : b33945ee-35a6-4dd0-9f4d-e5de4702cdd3
    type : Element
    shell : python
    code : print&#40;&#39;
Rapport de classification :&#39;&#41;
}
class inst_4329532592__Instruction{
    uid : 99a14a24-9a4c-41b0-8263-e34fe6c8947f
    type : Element
    shell : python
    code : print&#40;f&#39;Accuracy du modèle : &#123;accuracy:.2f&#125;&#39;&#41;
}
class inst_4329532432__Instruction{
    uid : da6a54b9-0797-411a-bfe7-4b0ac7b0c8fd
    type : Element
    shell : python
    code : accuracy = accuracy_score&#40;y_test, predictions&#41;
}
class inst_4329532112__Instruction{
    uid : 8cbf0b76-285f-4b6c-844a-3b6b745166ed
    type : Element
    shell : python
    code : predictions = model.predict&#40;X_test&#41;
}
class inst_4329850816__Step{
    uid : Model Evaluation
    type : Element
}
inst_4329850816__Step --> inst_4329532112__Instruction  : commands
inst_4329850816__Step --> inst_4329532432__Instruction  : commands
inst_4329850816__Step --> inst_4329532592__Instruction  : commands
inst_4329850816__Step --> inst_4329532752__Instruction  : commands
inst_4329850816__Step --> inst_4329532912__Instruction  : commands
inst_4329850816__Step --> inst_4329533072__Instruction  : commands
class inst_4329803712__Task{
    uid : ModelEvaluation
    type : Element
}
inst_4329803712__Task --> inst_4329850816__Step  : steps
inst_4329803712__Task --> inst_4329851088__Step  : steps
class inst_4329868816__Instruction{
    uid : 893fe816-37ee-4b15-9bda-b2c62254880e
    type : Element
    shell : python
    code : model.fit&#40;X_train, y_train&#41;;
}
class inst_4329430416__Step{
    uid : Fit Model
    type : Element
}
inst_4329430416__Step --> inst_4329868816__Instruction  : commands
class inst_4312643584__Instruction{
    uid : 2029872f-e1d9-4d8f-b002-d3919501d25d
    type : Element
    shell : python
    code : model = DecisionTreeClassifier&#40;random_state=42&#41;
}
class inst_4329803104__Step{
    uid : Model Training
    type : Element
}
inst_4329803104__Step --> inst_4312643584__Instruction  : commands
class inst_4329802800__Task{
    uid : ModelTraining
    type : Element
}
inst_4329802800__Task --> inst_4329803104__Step  : steps
inst_4329802800__Task --> inst_4329430416__Step  : steps
class inst_4329479568__Instruction{
    uid : 3179e812-514f-42b2-9d7d-5f2f9b99ead0
    type : Element
    shell : python
    code : X = df.drop&#40;&#39;species&#39;, axis=1&#41;
}
class inst_4329802496__Step{
    uid : DataPreparation
    type : Element
}
inst_4329802496__Step --> inst_4329479568__Instruction  : commands
class inst_4329412944__Task{
    uid : DataPreparation
    type : Element
}
inst_4329412944__Task --> inst_4329802496__Step  : steps
class inst_4329479952__Instruction{
    uid : e0980202-6a36-4220-8609-a5c2c1a524b3
    type : Element
    shell : python
    code : plt.show&#40;&#41;
}
class inst_4329736720__Instruction{
    uid : ec300c7d-fe31-48ab-bf73-b7666e0629f2
    type : Element
    shell : python
    code : plt.title&#40;&#39;Distribution de la longueur des pétales&#39;&#41;
}
class inst_4329060432__Instruction{
    uid : ac7ba844-c5c7-4cd5-b76d-014dcbb53a9e
    type : Element
    shell : python
    code : sns.histplot&#40;data=df, x=&#39;petal_length&#39;, hue=&#39;species&#39;, multiple=&#39;stack&#39;&#41;
}
class inst_4329055056__Instruction{
    uid : 0ab6a95b-85b8-4758-b5dc-4c586f665d16
    type : Element
    shell : python
    code : plt.figure&#40;figsize=&#40;8, 6&#41;&#41;
}
class inst_4329652304__Instruction{
    uid : 5ada2d3b-28c0-46ee-bd45-21f4bc7ea7ad
    type : Element
    shell : python
    code : plt.show&#40;&#41;
}
class inst_4328867792__Instruction{
    uid : 68bd0473-ae74-46f7-b90b-f834f5c6109b
    type : Element
    shell : python
    code : sns.pairplot&#40;df, hue=&#39;species&#39;&#41;
}
class inst_4329411984__Step{
    uid : Visualization
    type : Element
}
inst_4329411984__Step --> inst_4328867792__Instruction  : commands
inst_4329411984__Step --> inst_4329652304__Instruction  : commands
inst_4329411984__Step --> inst_4329055056__Instruction  : commands
inst_4329411984__Step --> inst_4329060432__Instruction  : commands
inst_4329411984__Step --> inst_4329736720__Instruction  : commands
inst_4329411984__Step --> inst_4329479952__Instruction  : commands
class inst_4329932368__Instruction{
    uid : d7cd99c3-850f-4ab5-8c56-3f0e8629e83c
    type : Element
    shell : python
    code : print&#40;df.head&#40;&#41;&#41;
}
class inst_4329931600__Instruction{
    uid : 0f97bc36-0b66-4a11-95dc-c9c0f99fd93b
    type : Element
    shell : python
    code : df = pd.DataFrame&#40;data=np.c_[iris[&#39;data&#39;], iris[&#39;target&#39;]]
}
class inst_4329850544__Instruction{
    uid : 4537e785-0d94-4aba-b074-dfd4269a0550
    type : Element
    shell : python
    code : iris = load_iris&#40;&#41;
}
class inst_4329411344__Step{
    uid : Load Dataset
    type : Element
}
inst_4329411344__Step --> inst_4329850544__Instruction  : commands
inst_4329411344__Step --> inst_4329931600__Instruction  : commands
inst_4329411344__Step --> inst_4329932368__Instruction  : commands
class inst_4329411024__Task{
    uid : DataLoading
    type : Element
}
inst_4329411024__Task --> inst_4329411344__Step  : steps
inst_4329411024__Task --> inst_4329411984__Step  : steps
class inst_4329850272__Instruction{
    uid : 0f9be982-6767-480c-9388-6c9a0426b607
    type : Element
    shell : python
    code : :from sklearn.datasets import load_iris
}
class inst_4329428688__Instruction{
    uid : d50da24c-9984-47ac-953e-4742416dfe18
    type : Element
    shell : python
    code : from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
}
class inst_4329802192__Instruction{
    uid : 12ef43da-d179-4c83-9dd9-b85207ff7969
    type : Element
    shell : python
    code : from sklearn.tree import DecisionTreeClassifier
}
class inst_4329801888__Instruction{
    uid : dceb15bb-bc68-4d9d-bd7e-d91c889c6e61
    type : Element
    shell : python
    code : from sklearn.model_selection import train_test_split
}
class inst_4329410704__Instruction{
    uid : 66e83889-8747-4bad-afdb-a8176078c969
    type : Element
    shell : python
    code : import seaborn as sns
}
class inst_4329410064__Instruction{
    uid : 3f43c545-a782-4008-87c8-34c376cffd49
    type : Element
    shell : python
    code : import matplotlib.pyplot as plt
}
class inst_4329508880__Instruction{
    uid : 8ae67fec-6097-4ca5-a833-6915fb699b90
    type : Element
    shell : python
    code : import numpy as np
}
class inst_4329508544__Step{
    uid : Import Libraries
    type : Element
}
inst_4329508544__Step --> inst_4329508880__Instruction  : commands
inst_4329508544__Step --> inst_4329410064__Instruction  : commands
inst_4329508544__Step --> inst_4329410704__Instruction  : commands
inst_4329508544__Step --> inst_4329801888__Instruction  : commands
inst_4329508544__Step --> inst_4329802192__Instruction  : commands
inst_4329508544__Step --> inst_4329428688__Instruction  : commands
inst_4329508544__Step --> inst_4329850272__Instruction  : commands
class inst_4329508208__Task{
    uid : LibraryLoading
    type : Element
}
inst_4329508208__Task --> inst_4329508544__Step  : steps
class inst_4329507200__Pipeline{
    uid : Iris Analysis Pipeline
    type : Element
}
inst_4329507200__Pipeline --> inst_4329508208__Task  : tasks
inst_4329507200__Pipeline --> inst_4329411024__Task  : tasks
inst_4329507200__Pipeline --> inst_4329412944__Task  : tasks
inst_4329507200__Pipeline --> inst_4329802800__Task  : tasks
inst_4329507200__Pipeline --> inst_4329803712__Task  : tasks
class Iris_Analysis_Pipeline_Manifest__PipelineManifest{
    uid : Classification on IRIS
    type : Element
    name : Iris Analysis Pipeline Manifest
    description :  classification ...
}
Iris_Analysis_Pipeline_Manifest__PipelineManifest --> inst_4329507200__Pipeline  : pipeline
Iris_Analysis_Pipeline_Manifest__PipelineManifest --> inst_4329507536__SoftwareFile  : artefacts
Iris_Analysis_Pipeline_Manifest__PipelineManifest --> Iris_Flower_Dataset__Data  : artefacts
Iris_Analysis_Pipeline_Manifest__PipelineManifest --> output_visualization__SoftwareFile  : artefacts
Iris_Analysis_Pipeline_Manifest__PipelineManifest --> Trained_Decision_Tree_Model__SoftwareFile  : artefacts
Iris_Analysis_Pipeline_Manifest__PipelineManifest --> Evaluation_Visualization__SoftwareFile  : artefacts
Iris_Analysis_Pipeline_Manifest__PipelineManifest --> Model_Accuracy__Metric  : artefacts
Iris_Analysis_Pipeline_Manifest__PipelineManifest --> Confusion_Matrix__Metric  : artefacts
Iris_Analysis_Pipeline_Manifest__PipelineManifest --> inst_4329507872__Relationship  : relations
Iris_Analysis_Pipeline_Manifest__PipelineManifest --> inst_4329411664__Relationship  : relations
Iris_Analysis_Pipeline_Manifest__PipelineManifest --> inst_4329412624__Relationship  : relations
Iris_Analysis_Pipeline_Manifest__PipelineManifest --> inst_4329803408__Relationship  : relations
Iris_Analysis_Pipeline_Manifest__PipelineManifest --> inst_4329804320__Relationship  : relations
Iris_Analysis_Pipeline_Manifest__PipelineManifest --> inst_4329430704__Relationship  : relations
Iris_Analysis_Pipeline_Manifest__PipelineManifest --> inst_4329851360__Relationship  : relations