classDiagram

class Iris_Analysis_Pipeline_Manifest__PipelineManifest {
uid: Classification on IRIS
type: Element
name: Iris Analysis Pipeline Manifest
description:  classification ...
creationInfo: None
properties: []
pipeline: Pipeline(uid='Iris Analysis Pipeline', type='Eleme...
artefacts: [SoftwareFile(uid='429c3dde-0e9e-49e1-9ace-22c982b...
relations: [Relationship(uid=PipelineManifest(uid='Classifica...
}